# Generated by Django 5.2.10 on 2026-01-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Camion",
            fields=[
                ("id_camion", models.AutoField(primary_key=True, serialize=False)),
                ("patente", models.CharField(max_length=10, unique=True)),
                (
                    "patente_remolque",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "vin",
                    models.CharField(blank=True, max_length=17, null=True, unique=True),
                ),
                ("marca", models.CharField(blank=True, max_length=50, null=True)),
                ("modelo", models.CharField(blank=True, max_length=50, null=True)),
                ("anio", models.IntegerField(blank=True, null=True)),
                ("tipo_camion", models.CharField(max_length=50)),
                ("tipo_carga", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "rol_operativo",
                    models.CharField(
                        choices=[("TITULAR", "Titular"), ("BACKUP", "Backup")],
                        max_length=10,
                    ),
                ),
                ("capacidad_m3", models.IntegerField()),
                (
                    "taller_mantencion",
                    models.CharField(
                        choices=[("ZMC", "ZMC"), ("KAUFMANN", "Kaufmann")],
                        max_length=10,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField()),
            ],
            options={
                "db_table": "camiones",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentoMantencion",
            fields=[
                ("id_documento", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_archivo", models.CharField(max_length=255)),
                ("ruta_archivo", models.TextField()),
                (
                    "tipo_documento",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("fecha_subida", models.DateTimeField()),
            ],
            options={
                "db_table": "documentos_mantencion",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EstadoCamion",
            fields=[
                ("id_estado", models.AutoField(primary_key=True, serialize=False)),
                ("kilometraje", models.IntegerField()),
                ("estado_operativo", models.CharField(max_length=20)),
                ("observacion", models.TextField(blank=True, null=True)),
                ("fecha_actualizacion", models.DateTimeField()),
            ],
            options={
                "db_table": "estado_camion",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HistorialEstadoCamion",
            fields=[
                ("id_historial", models.AutoField(primary_key=True, serialize=False)),
                ("kilometraje", models.IntegerField(blank=True, null=True)),
                ("estado_operativo", models.CharField(max_length=20)),
                ("id_conductor", models.IntegerField(blank=True, null=True)),
                ("descripcion_evento", models.TextField(blank=True, null=True)),
                ("fecha_evento", models.DateTimeField()),
            ],
            options={
                "db_table": "historial_estado_camion",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Mantencion",
            fields=[
                ("id_mantencion", models.AutoField(primary_key=True, serialize=False)),
                ("taller", models.CharField(max_length=10)),
                ("fecha_mantencion", models.DateField()),
                ("km_mantencion", models.IntegerField(blank=True, null=True)),
                ("km_proxima_mantencion", models.IntegerField(blank=True, null=True)),
                ("km_restantes", models.IntegerField(blank=True, null=True)),
                ("dias_revision_tecnica", models.IntegerField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField()),
            ],
            options={
                "db_table": "mantenciones",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Conductor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("rut", models.CharField(max_length=20, unique=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("correo", models.EmailField(blank=True, max_length=254, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Conductor",
                "verbose_name_plural": "Conductores",
            },
        ),
        migrations.CreateModel(
            name="DocumentacionGeneral",
            fields=[
                ("id_documento", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo_entidad",
                    models.CharField(
                        choices=[("CAMION", "Camión"), ("CONDUCTOR", "Conductor")],
                        max_length=10,
                    ),
                ),
                (
                    "id_referencia",
                    models.IntegerField(
                        help_text="ID del camión o conductor según el tipo de entidad"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("LICENCIA", "Licencia de Conducir"),
                            ("EXTINTOR", "Extintor"),
                            ("REVISION_TECNICA", "Revisión Técnica"),
                            ("SEGURO", "Seguro / SOAP"),
                            ("PERMISO_CIRCULACION", "Permiso de Circulación"),
                        ],
                        max_length=50,
                    ),
                ),
                ("fecha_vencimiento", models.DateField()),
                ("url_drive", models.URLField(max_length=500)),
            ],
            options={
                "verbose_name": "Documento General",
                "db_table": "documentos_general",
                "ordering": ["fecha_vencimiento"],
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("rut", models.CharField(max_length=20, unique=True)),
                ("activa", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
