# Generated by Django 5.2.10 on 2026-02-04 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Remolque",
            fields=[
                (
                    "id_remolque",
                    models.AutoField(
                        db_column="id_remolque", primary_key=True, serialize=False
                    ),
                ),
                (
                    "patente",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Patente"
                    ),
                ),
                ("marca", models.CharField(blank=True, max_length=100, null=True)),
                ("modelo", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "anio",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Año"
                    ),
                ),
                (
                    "tipo_remolque",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "capacidad_carga",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("n_ejes", models.PositiveIntegerField(default=2)),
                (
                    "kilometraje_acumulado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Suma de kilómetros recorridos por los tractos asignados",
                        max_digits=12,
                    ),
                ),
                (
                    "estado_operativo",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("mantenimiento", "En Mantención"),
                            ("ruta", "En Ruta"),
                            ("baja", "De Baja"),
                        ],
                        default="disponible",
                        max_length=50,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Remolque",
                "verbose_name_plural": "Remolques",
                "db_table": "remolques",
            },
        ),
        migrations.AlterModelOptions(
            name="documentaciongeneral",
            options={
                "managed": False,
                "ordering": ["fecha_vencimiento"],
                "verbose_name": "Documento General",
            },
        ),
        migrations.CreateModel(
            name="HistorialEstadoRemolque",
            fields=[
                (
                    "id_historial",
                    models.AutoField(
                        db_column="id_historial", primary_key=True, serialize=False
                    ),
                ),
                ("kilometraje", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "estado_operativo",
                    models.CharField(
                        choices=[
                            ("OPERATIVO", "Operativo"),
                            ("EN_MANTENCION", "En Mantención"),
                            ("NO_OPERATIVO", "No Operativo"),
                            ("FUERA_DE_SERVICIO", "Fuera de Servicio"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "descripcion_evente",
                    models.TextField(db_column="descripcion_evente"),
                ),
                (
                    "fecha_evento",
                    models.DateTimeField(auto_now_add=True, db_column="fecha_evento"),
                ),
                (
                    "remolque",
                    models.ForeignKey(
                        db_column="id_remolque",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.remolque",
                    ),
                ),
            ],
            options={
                "db_table": "historial_estado_remolque",
            },
        ),
        migrations.CreateModel(
            name="EstadoRemolque",
            fields=[
                (
                    "id_estado",
                    models.AutoField(
                        db_column="id_estado_remolque",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "estado_operativo",
                    models.CharField(
                        choices=[
                            ("OPERATIVO", "Operativo"),
                            ("EN_MANTENCION", "En Mantención"),
                            ("NO_OPERATIVO", "No Operativo"),
                            ("FUERA_DE_SERVICIO", "Fuera de Servicio"),
                        ],
                        default="OPERATIVO",
                        max_length=20,
                    ),
                ),
                ("observacion", models.TextField(blank=True, null=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "remolque",
                    models.OneToOneField(
                        db_column="id_remolque",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estado_actual",
                        to="core.remolque",
                    ),
                ),
            ],
            options={
                "db_table": "estado_remolque",
            },
        ),
        migrations.CreateModel(
            name="AsignacionTractoRemolque",
            fields=[
                (
                    "id_asignacion",
                    models.AutoField(
                        db_column="id_asignacion", primary_key=True, serialize=False
                    ),
                ),
                ("fecha_desde", models.DateTimeField(auto_now_add=True)),
                ("fecha_hasta", models.DateTimeField(blank=True, null=True)),
                (
                    "km_inicio_camion",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Kilometraje del camión al momento de realizar el enganche",
                        max_digits=12,
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el remolque está actualmente enganchado a este camión",
                    ),
                ),
                (
                    "camion",
                    models.ForeignKey(
                        db_column="id_camion",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.camion",
                    ),
                ),
                (
                    "remolque",
                    models.ForeignKey(
                        db_column="id_remolque",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.remolque",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación Tracto-Remolque",
                "verbose_name_plural": "Asignaciones Tracto-Remolque",
                "db_table": "asignacion_tracto_remolque",
            },
        ),
    ]
