# Generated by Django 5.2.10 on 2026-02-04 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_remolque_alter_documentaciongeneral_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("orden", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Inspeccion",
            fields=[
                ("id_inspeccion", models.AutoField(primary_key=True, serialize=False)),
                ("kilometraje_unidad", models.IntegerField()),
                ("fecha_ingreso", models.DateTimeField()),
                ("fecha_salida", models.DateTimeField(blank=True, null=True)),
                ("responsable", models.CharField(max_length=100)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("apto_operacion", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "camion",
                    models.ForeignKey(
                        db_column="id_camion",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspecciones",
                        to="core.camion",
                    ),
                ),
                (
                    "remolque",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_remolque",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspecciones",
                        to="core.remolque",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inspecciones",
                "db_table": "mantencion_inspeccion",
            },
        ),
        migrations.CreateModel(
            name="ItemChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("es_critico", models.BooleanField(default=False)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="mantenciones.categoriachecklist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroLubricantes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_lubricante", models.CharField(max_length=100)),
                ("renovado", models.BooleanField(default=False)),
                ("proximo_cambio_km", models.IntegerField(blank=True, null=True)),
                (
                    "inspeccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lubricantes",
                        to="mantenciones.inspeccion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResultadoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("B", "Bueno"), ("R", "Regular"), ("M", "Malo")],
                        default="B",
                        max_length=1,
                    ),
                ),
                (
                    "observacion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="inspecciones/evidencia/"
                    ),
                ),
                (
                    "inspeccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="mantenciones.inspeccion",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mantenciones.itemchecklist",
                    ),
                ),
            ],
            options={
                "unique_together": {("inspeccion", "item")},
            },
        ),
    ]
