# Generated by Django 5.2.10 on 2026-02-17 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_remolque_alter_documentaciongeneral_options_and_more"),
    ]

    operations = [
    
        migrations.CreateModel(
            name="RegistroDiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revisado_por",
                    models.CharField(
                        help_text="Nombre de quien realiza la inspección",
                        max_length=100,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "km_actual",
                    models.PositiveIntegerField(verbose_name="Kilometraje actual"),
                ),
                (
                    "horometro",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Horómetro (opcional)"
                    ),
                ),
                (
                    "es_apto",
                    models.BooleanField(
                        default=True, verbose_name="¿Apto para operar?"
                    ),
                ),
                (
                    "nivel_combustible",
                    models.CharField(
                        choices=[
                            ("bajo", "Bajo"),
                            ("medio", "Medio"),
                            ("full", "Full"),
                        ],
                        default="full",
                        max_length=20,
                    ),
                ),
                (
                    "check_datos",
                    models.JSONField(
                        default=dict, help_text="Resultados del checklist diario"
                    ),
                ),
                (
                    "novedades",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Novedades o fallas detectadas",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklists_diarios",
                        to="core.camion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro Diario",
                "verbose_name_plural": "Registros Diarios",
                "ordering": ["-fecha"],
            },
        ),
       
    ]
