# Generated by Django 5.2.10 on 2026-02-27 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remolque_alter_documentaciongeneral_options_and_more"),
        ("mantenciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("orden", models.IntegerField(default=0)),
                (
                    "aplica_a",
                    models.CharField(
                        choices=[
                            ("DIARIO", "Solo Checklist Diario"),
                            ("MANTENCION", "Solo Mantención Técnica"),
                            ("AMBOS", "Aplica a Ambos"),
                        ],
                        default="AMBOS",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inspeccion",
            fields=[
                (
                    "tipo_inspeccion",
                    models.CharField(
                        choices=[
                            ("DIARIO", "Checklist Diario"),
                            ("MANTENCION", "Mantención Técnica"),
                        ],
                        default="DIARIO",
                        max_length=20,
                    ),
                ),
                ("id_inspeccion", models.AutoField(primary_key=True, serialize=False)),
                ("km_registro", models.PositiveIntegerField()),
                ("fecha_ingreso", models.DateTimeField(auto_now_add=True)),
                ("fecha_salida", models.DateTimeField(blank=True, null=True)),
                (
                    "responsable",
                    models.CharField(default="Tomás Rocamora", max_length=100),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "es_apto_operar",
                    models.BooleanField(
                        default=True, verbose_name="¿Apto para operar?"
                    ),
                ),
                (
                    "renovó_aceite",
                    models.BooleanField(
                        default=False, verbose_name="¿Renovó Aceite Motor?"
                    ),
                ),
                ("ajuste_db", models.BooleanField(default=True)),
                (
                    "remolque",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_remolque",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspecciones",
                        to="core.remolque",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        db_column="id_camion",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspecciones",
                        to="core.camion",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inspecciones",
                "db_table": "mantencion_inspeccion",
            },
        ),
        migrations.CreateModel(
            name="ItemChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("es_critico", models.BooleanField(default=False)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="mantenciones.categoriachecklist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroLubricantes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_lubricante", models.CharField(max_length=100)),
                ("renovado", models.BooleanField(default=False)),
                ("proximo_cambio_km", models.IntegerField(blank=True, null=True)),
                (
                    "inspeccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lubricantes",
                        to="mantenciones.inspeccion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResultadoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("B", "Bueno"), ("R", "Regular"), ("M", "Malo")],
                        default="B",
                        max_length=1,
                    ),
                ),
                (
                    "observacion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="inspecciones/evidencia/"
                    ),
                ),
                (
                    "inspeccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="mantenciones.inspeccion",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mantenciones.itemchecklist",
                    ),
                ),
            ],
            options={
                "unique_together": {("inspeccion", "item")},
            },
        ),
    ]
