# Generated by Django 5.2.10 on 2026-02-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mantenciones", "0002_categoriachecklist_inspeccion_itemchecklist_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoriachecklist",
            name="aplica_a",
        ),
        migrations.AddField(
            model_name="categoriachecklist",
            name="filtro_tipo",
            field=models.CharField(
                choices=[
                    ("DIARIO", "Solo Checklist Diario"),
                    ("MANTENCION", "Solo Mantención Técnica"),
                    ("AMBOS", "Aplica a Ambos"),
                ],
                default="AMBOS",
                max_length=20,
            ),
        ),
    ]
